name: dict-updater

on:
  schedule:
    - cron: '0 0 * * *'  # UTC 时间每天 0 点
  workflow_dispatch:

jobs:
  update-dictionary:
    runs-on: ubuntu-latest
    
    steps:
    # 第一步：检出仓库（保留历史文件）
    - name: Checkout with existing files
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # 第二步：下载最新词库 ZIP
    - name: Download dictionary
      run: |
        curl -L -o cn_dicts.zip \
        https://github.com/amzxyz/RIME-LMDG/releases/download/dict-nightly/cn_dicts.zip

    # 第三步：智能解压覆盖
    - name: Smart unzip
      run: |
        mkdir temp_unzip
        unzip -o cn_dicts.zip -d temp_unzip/
        cp -f -r temp_unzip/* .
        rm -rf temp_unzip

    # 第四步：智能提交（仅当有变更时）
    - name: Conditional Commit
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add cn_dict/
        git commit -m "增量更新词库 (夜间构建)"
        git push origin main

    # 可选的变更日志生成
    - name: Generate Change Log
      run: |
        git diff --name-status HEAD^ cn_dict/ > changes.log
        echo "CHANGED_FILES=$(cat changes.log | grep '^[AM]' | cut -f2 | tr '\n' ' ')" >> $GITHUB_ENV
        
      # 上传log
    - name: Upload Log
      uses: actions/upload-artifact@v4
      with:
        name: change-log
        path: changes.log
