name: Sync Upstream

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 0 点运行
  workflow_dispatch:     # 允许手动触发

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout current repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 获取完整提交历史

    - name: Configure Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Add upstream remote
      run: git remote add upstream https://github.com/gaboolic/rime-frost.git

    - name: Fetch upstream changes
      run: git fetch upstream main

    - name: Check for changes
      id: check-changes
      run: |
        # 比较当前分支与上游差异（排除词库目录）
        if ! git diff --exit-code main..upstream/main -- . ':!cn_dicts'; then
          echo "has_changes=true" >> $GITHUB_OUTPUT
        fi

    - name: Merge changes (excluding dicts)
      if: steps.check-changes.outputs.has_changes == 'true'
      run: |
        # 重置到上游版本（但保留工作区文件）
        git reset --soft upstream/main
        
        # 撤销对词库目录的更改
        git restore --staged cn_dicts/
        git restore cn_dicts/
        
        # 提交变更
        git commit -m "Sync upstream changes (excluded cn_dicts)"
        git push origin main